language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
#
script:
  - cd tests
  - pip freeze
  - python -m pytest test_xsd_validation.py
  
