language: python
python:
  - "2.7.11"
# command to install dependencies
install:
  - "sudo apt-get install libxml2-dev libxslt-dev python-dev"
  - "sudo apt-get install python-lxml"
  - "pip install -r requirements.txt"

script:
  - cd tests
  - pip freeze
  - python -m pytest test_xsd_validation.py
